### ISSUE TITLE
Problem in org files

### ISSUE THREAD

**Issue by dinkonin** [Kungsgeten/yankpad#20]
Hello I'm using yankpad 20170523.235 in Emacs 25.2 (Windows) and the latest org-mode.
My initial startup mode is org-mode
When I launch emacs, yankpad refuses to work in the scratch buffer , if i visit a new file it works.
Additionaly if i open an org with a hotkey file like this: `(global-set-key (kbd "C-c e") (lambda() (interactive)(find-file "~/.emacs.d/init.org")))` it does not seem to work.
this is  my yankpad-config:
```
  (use-package yankpad
    :ensure t
    :bind     (("<f7>" . yankpad-map)        ; Change category
               ("C-M-x" . yankpad-expand))
    :init
    (setq yankpad-file "~/.emacs.d/snippets.org") )
```

And this is my snippets.org file:
```
* org-mode
** el: Insert elisp SRC block
#+BEGIN_SRC emacs-lisp

#+END_SRC
```

Am i missing something?

**Comment by Kungsgeten** [comment]
Hi! I'm not 100% sure, but this is what I think happens:

The `bind` keyword in `use-package` means that `yankpad` isn't loaded until you use the bindings, `f7` and `C-M-x` in your case. Upon loading yankpad, a function is added to `after-change-major-mode-hook`, and this function set the yankpad category to the major mode (if available). Since yankpad isn't loaded when you visit the org-file (I guess), this function haven't been added to the hook yet, and thus it will not change category to your `org-mode` category.

You could try adding `:demand t` in the `use-package` declaration. Another option could be to use `M-x yankpad-set-category`, if you notice that it doesn't work on the first file.

**Comment by dinkonin** [comment]
Hello , adding `:demand t` and manualy setting the category both worked. Could it be fixed by detecting that no category is set when executing `yankpad-extend` and tring to detect/set it. I could try and do a PR but I'm very new to elisp and it will be embarissingly bad code for sure.

**Comment by Kungsgeten** [comment]
I've added a commit which try to set the category upon loading yankpad, I think that should solve the problem. It will probably take a couple of hours before it is up on MELPA, but please try again later today or tomorrow and please notify me if it fixes the problem :)

**Comment by dinkonin** [comment]
Unfortunately the problem persists even with the latest commit, but I think i have found a workaround for me. When i add  
```
(unless yankpad-category
    (yankpad-set-category))
``` 
on top of `yankpad-expand ()` in `yankpad.el` it prompts me once to set the catagory and then it works

**Comment by Kungsgeten** [comment]
Are you sure that the commit doesn't work? It seems to be working for me. The latest version should be on MELPA now, so please update the package and try again.

I do like your pull request though, since `yankpad-expand` probably should ask for a category if there is none.

**Comment by dinkonin** [comment]
Yes , it was not working for without the PR merge, it's perfect now.  Thank you and cheers.
