### ISSUE TITLE
yankpad-category

### ISSUE THREAD

**Issue by indigoviolet** [Kungsgeten/yankpad#44]
Can we set a default category for major-modes that don't have a section defined?

**Comment by Kungsgeten** [comment]
That was a quick fix! I've added so that if you have a category named `Default` it will be used if no major-mode specific category is found. You probably want to add the `:global:` tag to this as well, so that its always available even if a major-mode specific category is found (but I guess it depends on your use case).

**Comment by indigoviolet** [comment]
Thanks for the super quick fix, that's awesome!
